Gui evolution xd
nornes/tiles-rapIoT pull request #49
Opened 2017-03-25 14:41 UTC by KevinMidboe

This branch has added functionality mainly in the virtual tiles view and also some for the applications.

2017-03-25 16:42 UTC, nornes requested changes
Can the ble service file be removed from the PR? Doesn't seem like you have done anything except add an unused import and remove a few alerts.

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/pages/applications/applications.ts
> +        this.setApplications();
Great minds think alike :P I did this in the branch I am working with too :)

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/pages/virtual-tiles/virtual-tiles.ts
> +  pairedVirtualTiles = [];
Wouldn't it work to map over the tiles to check if paired or not instead? Seems redundant to store them twice.

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/pages/virtual-tiles/virtual-tiles.ts
> +    if (this.devices.length > 0) {
Makes a lot of sense. Like it!

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/pages/virtual-tiles/virtual-tiles.ts
> +  unpairTile = (virtualTile: VirtualTile): void => {
We do not have an api endpoint for this. You can only pair with a new one.

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/providers/ble.service.ts
> +import { Events, AlertController } from 'ionic-angular';
why?

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/providers/ble.service.ts
> +              private alertCtrl: AlertController) {
again, why?

2017-03-25 16:42 UTC, nornes commented on GATEWAY/src/providers/ble.service.ts
Why was this file even added to the PR?

2017-03-26 10:38 UTC, eivindsandell approved these changes
Good shit

2017-03-26 12:03 UTC, nornes approved these changes

2017-03-26 12:09 UTC, merged